tabs:
- title: 首页
  id: home
  icon: mdi-home
  readme: 首页，启动后自动自检
  router: custom1
- title: 装备检测
  id: about
  icon: mdi-checkbox-multiple-marked-circle-outline
  readme: ETestVue是ETestDev的UI组件库
  router: custom3
- title: 故障诊断
  id: tree
  icon: mdi-car-tire-alert
  readme: 树结构组件：用于绑定树形结构数据的UI组件
  router: custom2
- title: 维修日志
  id: runcase
  icon: mdi-comment-edit-outline
  readme: 用例执行组件：包含执行控制按钮、执行输出两个独立的组件
  router: Lists
- title: 技术资料
  id: watcher
  icon: mdi-book-open-outline
  readme: 实时监视组件：用于实时监视用例执行状态数据，可任意组合搭配使用
  router: custom4
- title: 装备履历
  id: analysis
  icon: mdi-car-info
  readme: 数据分析组件：用于对采集数据进行穿透查询或数据分析
  router: Report
- title: 系统信息
  id: lists
  icon: mdi-cog-outline
  readme: 选择列表组件：用于从多项内容中选择
  router: Analysis_regression1
- title: 退出
  id: exit
  icon: mdi-exit-run
  readme: 退出程序